{% set name = "pyreadline3" %}
{% set version = "3.5.4" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyreadline3-{{ version }}.tar.gz
  sha256: 8d57d53039a1c75adba8e50dd3d992b28143480816187ea5efbd5c78e6c885b7

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not win]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - pip
    - python
    - sphinx
    - setuptools
  run:
    - python

test:
  imports:
    - pyreadline3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.python.org/pypi/pyreadline3/
  summary: A python implementation of GNU readline.
  license: BSD-3-Clause
  license_file: doc/COPYING

extra:
  recipe-maintainers:
    - tschoonj
