{% set name = "pyreadline3" %}
{% set version = "3.4.3" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyreadline3-{{ version }}.tar.gz
  sha256: ebab0baca37f50e2faa1dd99a6da1c75de60e0d68a3b229c134bbd12786250e2

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not win]

requirements:
  host:
    - pip
    - python
    - sphinx
    - setuptools
  run:
    - python

test:
  imports:
    - pyreadline3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.python.org/pypi/pyreadline3/
  summary: A python implementation of GNU readline.
  license: BSD-3-Clause
  license_file: doc/COPYING

extra:
  recipe-maintainers:
    - tschoonj
