{% set name = "pyreadline3" %}
{% set version = "3.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pyreadline3-{{ version }}.tar.gz
  sha256: 06041dd3b0cc7b672a48dcab378d0d28e480d1f76b793ee74cb94d3cabc32335

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [not win]

requirements:
  host:
    - pip
    - python
    - sphinx
    - setuptools
  run:
    - python

test:
  imports:
    - pyreadline3
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.python.org/pypi/pyreadline3/
  summary: A python implementation of GNU readline.
  license: BSD-3-Clause
  license_file: doc/COPYING

extra:
  recipe-maintainers:
    - tschoonj
